on:
  push:
    branches: [staging, trying, master]
  pull_request:

name: Continuous integration

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [stable]

        # The default target we're compiling on and for
        TARGET:
          [x86_64-unknown-linux-gnu, thumbv6m-none-eabi, thumbv7m-none-eabi]

        include:
          # Test MSRV
          - rust: 1.77.0
            TARGET: x86_64-unknown-linux-gnu

          # Test nightly but don't fail
          - rust: nightly
            experimental: true
            TARGET: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.TARGET }}
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=${{ matrix.TARGET }}

  ci-linux-async:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        TARGET:
          [x86_64-unknown-linux-gnu, thumbv6m-none-eabi, thumbv7m-none-eabi]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.TARGET }}
      - run: cargo check --target=${{ matrix.TARGET }}
        working-directory: embedded-nal-async
      - run: cargo test --target=${{ matrix.TARGET }}
        if: contains(matrix.TARGET, 'linux')
        working-directory: embedded-nal-async
